name: persist
version: 0.0.3
author: James Ots <code@jamesots.com>
description: DB Persistence Stuff
homepage: https://github.com/jamesots/persist
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  sqljocky: '>=0.11.0 <2.0.0'
dev_dependencies:
  unittest: '>=0.9.0 <0.10.0'
  options_file: '>=0.9.15'
  logging: '>=0.9.0 <0.10.0'
